apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo1-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  selector:
    matchLabels:
      app: demo1
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: demo1
    spec:
      serviceAccountName: demo1-sa
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: demo1
        image: rodriguesflavio/demo1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demo1-service
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: demo1
  ports:
    - name: http
      port: 8080
      nodePort: 30080
  type: NodePort
